### ISSUE TITLE
setup.py and source tarballs

### ISSUE THREAD

**Issue by ghost** [nlhepler/pydot#1]
Thank you very much for this initiative.
Is it possible to address a couple of remaining issues?
1. in the setup, this line is rather unorthodox:

```
    data_files = [('.', ['LICENSE', 'README'])] )
```

it might be better to put everything into a pydot subdirectory to coexist with other python modules.
2. for pkgsrc, we typically use the gzipped tarball for the source download, currently  http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz as indicated on https://pypi.python.org/pypi/pydot. Do you plan on updating this or providing an alternative?

**Comment by nlhepler** [comment]
1) The setup is definitely fixable.
2) I would have to negotiate something with the original maintainer in order to get that working, unless we wanted to change the package name.

**Comment by ghost** [comment]
My personal belief is that it would be best to keep one distro as certain packages, for instance tryton, use pydot... Perhaps with the collaboration of the original maintainer, scm could move to github (or at least mirrored), and use pypi directly (instead of googlecode) for the source code tarballs. Everybody is a winner in this case.

**Comment by gill1109** [comment]
Can someone please explain to me how I can install this? There is no release, right, just a couple of files: "**init**.py", "_dotparser.py", "setup.py". I also have the source for pydot_1.0.28. And it is installed but .. what do I do next? [sorry for this newby question. My aim is to get dot2tex working under Mac OS10.9.]

pydot gets installed using easy_install but doesn't know how to handle dot files. dot2tex is also installed but crashes when called, "ImportError: cannot import name _noncomma"

Below are the gruesome details

Richards-MacBook-Pro:pydot root# easy_install pydot
Searching for pydot
Reading http://pypi.python.org/simple/pydot/
Reading http://code.google.com/p/pydot/
Reading http://dkbza.org/pydot.html
Best match: pydot 1.0.28
Downloading http://pydot.googlecode.com/files/pydot-1.0.28.zip
Processing pydot-1.0.28.zip
Running pydot-1.0.28/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RSpLNS/pydot-1.0.28/egg-dist-tmp-wrqXNy

Couldn't import dot_parser, loading of dot files will not be possible.
zip_safe flag not set; analyzing archive contents...
Adding pydot 1.0.28 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/pydot-1.0.28-py2.7.egg
Processing dependencies for pydot
Finished processing dependencies for pydot

Richards-MacBook-Pro:pydot root# dot2tex
Traceback (most recent call last):
  File "/usr/local/bin/dot2tex", line 2, in <module>
    from dot2tex.dot2tex import main
  File "/Library/Python/2.7/site-packages/dot2tex/**init**.py", line 36, in <module>
    import dot2tex as d2t
  File "/Library/Python/2.7/site-packages/dot2tex/dot2tex.py", line 47, in <module>
    import dotparsing
  File "/Library/Python/2.7/site-packages/dot2tex/dotparsing.py", line 26, in <module>
    from pyparsing import  (Literal, CaselessLiteral, Word, Upcase, OneOrMore, ZeroOrMore,
ImportError: cannot import name _noncomma

**Comment by nlhepler** [comment]
Hi Richard,

You're installing the original version of pydot. The version here is a
forked copy designed to work under the latest 2.7 and 3.3 releases of
Python. You'll have to install it manually (not using easy_install -- I
have no control over the version of pydot on pypi). To install this fork,
get a copy of the source from github, and `./python setup.py install` from
the source directory (where setup.py resides).

Sorry for the confusion. The problems you're having with the original pydot
are the reasons for this fork.

**Comment by gill1109** [comment]
Hi thanks for the advice. I am working with Python 2.7, Mac OS 10.9.1 (Maverick). Have installed your pydot-1.0.28 downloaded from here, succesfully I believe, and before that, pyparsing-2.0.1, and after that, dot2tex-2.8.7 (all in my site-packages directory). 

Still getting the identical "cannot import name _noncomma" error

**Comment by nlhepler** [comment]
That's weird, because _noncomma is defined in my version of pydot, not
imported. I haven't made any releases--there are issues regarding the
original author of the package that need to be resolved. To install this
version, please make sure you've `git clone
github.com/nlhepler/pydot`'d<http://github.com/nlhepler/pydot'd>locally,
and installed from there. The only hiccup I can think of is that
you might need to manually remove the old version of pydot you installed
(with easy_install) before doing so, depending on how you went about it. As
an aside, I highly recommend using pip for package installation -- you can
install packages from local source using `pip install -I .` from within the
source directory (in lieu of `python setup.py install`), and install
packages from pypi as you would with easy_install, and it will also
uninstall and upgrade packages for you, functionality the other tools do
not provide.

**Comment by gill1109** [comment]
I don't have git installed, but got your pydot (?) from https://github.com/nlhepler/pydot/archive/master.zip

I think I had completely removed previous versions of pydot but maybe I am mistaken. I have a lot to learn about managing Python. I also have graphviz installed through mac ports and maybe that has also brought in some duplicate python stuff.

Maybe dot2tex needs to be patched so as to know which pydot to use.

Richards-MacBook-Pro:Desktop richard$ dot2tex G.xdot
Traceback (most recent call last):
  File "/usr/local/bin/dot2tex", line 2, in <module>
    from dot2tex.dot2tex import main
  File "/Library/Python/2.7/site-packages/dot2tex/**init**.py", line 36, in <module>
    import dot2tex as d2t
  File "/Library/Python/2.7/site-packages/dot2tex/dot2tex.py", line 47, in <module>
    import dotparsing
  File "/Library/Python/2.7/site-packages/dot2tex/dotparsing.py", line 26, in <module>
    from pyparsing import  (Literal, CaselessLiteral, Word, Upcase, OneOrMore, ZeroOrMore,
ImportError: cannot import name _noncomma

**Comment by nlhepler** [comment]
Ah, from the stack trace things actually look okay on the pydot front --
but dot2tex seems to have a heavily-modified, older copy of dotparsing.py
from pydot within it? Looking at the source (
http://code.google.com/p/dot2tex/source/browse/dot2tex/dotparsing.py),
though, it looks like _noncomma is imported but then not even used. Try
modifying the source, removing the _noncomma import, and see if that fixes
your error.

**Comment by gill1109** [comment]
Yes that worked!!!! Brilliant, and thanks a lot.
